sudo: required
services:
  - docker

before_install:
  - docker build -t kei178/go-mongo-api -f ./api/Dockerfile.dev ./api/
  - docker run --name mongodb -d mongo:latest

script:
  - docker run -e CI=true --link mongodb:mongo -it kei178/go-mongo-api go test -v 