sudo: required
services:
  - docker

before_install:
  - docker build -t kei178/go-mongo-api -f ./api/Dockerfile.dev ./api/

script:
  - docker run --name mongodb -d mongo:latest
  - docker run -e CI=true --link mongodb:mongo -it kei178/go-mongo-api go test -v 

# TODO: Pending: The Travis CI build is in progress... mongo container is problem?
